from collections import OrderedDict

version_commands = {
  "2.1": [
    "glAccum",
    "glActiveTexture",
    "glAlphaFunc",
    "glAreTexturesResident",
    "glArrayElement",
    "glAttachShader",
    "glBeginQuery",
    "glBegin",
    "glBindAttribLocation",
    "glBindBuffer",
    "glBindTexture",
    "glBitmap",
    "glBlendColor",
    "glBlendEquationSeparate",
    "glBlendEquation",
    "glBlendFuncSeparate",
    "glBlendFunc",
    "glBufferData",
    "glBufferSubData",
    "glCallLists",
    "glCallList",
    "glClearAccum",
    "glClearColor",
    "glClearDepth",
    "glClearIndex",
    "glClearStencil",
    "glClear",
    "glClientActiveTexture",
    "glClipPlane",
    "glColorMask",
    "glColorMaterial",
    "glColorPointer",
    "glColorSubTable",
    "glColorTableParameter",
    "glColorTable",
    "glColor",
    "glCompileShader",
    "glCompressedTexImage1D",
    "glCompressedTexImage2D",
    "glCompressedTexImage3D",
    "glCompressedTexSubImage1D",
    "glCompressedTexSubImage2D",
    "glCompressedTexSubImage3D",
    "glConvolutionFilter1D",
    "glConvolutionFilter2D",
    "glConvolutionParameter",
    "glCopyColorSubTable",
    "glCopyColorTable",
    "glCopyConvolutionFilter1D",
    "glCopyConvolutionFilter2D",
    "glCopyPixels",
    "glCopyTexImage1D",
    "glCopyTexImage2D",
    "glCopyTexSubImage1D",
    "glCopyTexSubImage2D",
    "glCopyTexSubImage3D",
    "glCreateProgram",
    "glCreateShader",
    "glCullFace",
    "glDeleteBuffers",
    "glDeleteLists",
    "glDeleteProgram",
    "glDeleteQueries",
    "glDeleteShader",
    "glDeleteTextures",
    "glDepthFunc",
    "glDepthMask",
    "glDepthRange",
    "glDetachShader",
    "glDisableClientState",
    "glDisableVertexAttribArray",
    "glDisable",
    "glDrawArrays",
    "glDrawBuffers",
    "glDrawBuffer",
    "glDrawElements",
    "glDrawPixels",
    "glDrawRangeElements",
    "glEdgeFlagPointer",
    "glEdgeFlag",
    "glEnableClientState",
    "glEnableVertexAttribArray",
    "glEnable",
    "glEndList",
    "glEndQuery",
    "glEnd",
    "glEvalCoord",
    "glEvalMesh",
    "glEvalPoint",
    "glFeedbackBuffer",
    "glFinish",
    "glFlush",
    "glFogCoordPointer",
    "glFogCoord",
    "glFog",
    "glFrontFace",
    "glFrustum",
    "glGenBuffers",
    "glGenLists",
    "glGenQueries",
    "glGenTextures",
    "glGetActiveAttrib",
    "glGetActiveUniform",
    "glGetAttachedShaders",
    "glGetAttribLocation",
    "glGetBufferParameteriv",
    "glGetBufferPointerv",
    "glGetBufferSubData",
    "glGetClipPlane",
    "glGetColorTableParameter",
    "glGetColorTable",
    "glGetCompressedTexImage",
    "glGetConvolutionFilter",
    "glGetConvolutionParameter",
    "glGetError",
    "glGetHistogramParameter",
    "glGetHistogram",
    "glGetLight",
    "glGetMap",
    "glGetMaterial",
    "glGetMinmaxParameter",
    "glGetMinmax",
    "glGetPixelMap",
    "glGetPointerv",
    "glGetPolygonStipple",
    "glGetProgramInfoLog",
    "glGetProgram",
    "glGetQueryiv",
    "glGetQueryObject",
    "glGetSeparableFilter",
    "glGetShaderInfoLog",
    "glGetShaderSource",
    "glGetShader",
    "glGetString",
    "glGetTexEnv",
    "glGetTexGen",
    "glGetTexImage",
    "glGetTexLevelParameter",
    "glGetTexParameter",
    "glGetUniformLocation",
    "glGetUniform",
    "glGetVertexAttribPointerv",
    "glGetVertexAttrib",
    "glGet",
    "glHint",
    "glHistogram",
    "glIndexMask",
    "glIndexPointer",
    "glIndex",
    "glInitNames",
    "glInterleavedArrays",
    "glIsBuffer",
    "glIsEnabled",
    "glIsList",
    "glIsProgram",
    "glIsQuery",
    "glIsShader",
    "glIsTexture",
    "glLightModel",
    "glLight",
    "glLineStipple",
    "glLineWidth",
    "glLinkProgram",
    "glListBase",
    "glLoadIdentity",
    "glLoadMatrix",
    "glLoadName",
    "glLoadTransposeMatrix",
    "glLogicOp",
    "glMap1",
    "glMap2",
    "glMapBuffer",
    "glMapGrid",
    "glMaterial",
    "glMatrixMode",
    "glMinmax",
    "glMultiDrawArrays",
    "glMultiDrawElements",
    "glMultiTexCoord",
    "glMultMatrix",
    "glMultTransposeMatrix",
    "glNewList",
    "glNormalPointer",
    "glNormal",
    "glOrtho",
    "glPassThrough",
    "glPixelMap",
    "glPixelStore",
    "glPixelTransfer",
    "glPixelZoom",
    "glPointParameter",
    "glPointSize",
    "glPolygonMode",
    "glPolygonOffset",
    "glPolygonStipple",
    "glPopAttrib",
    "glPopClientAttrib",
    "glPopMatrix",
    "glPopName",
    "glPrioritizeTextures",
    "glPushAttrib",
    "glPushClientAttrib",
    "glPushMatrix",
    "glPushName",
    "glRasterPos",
    "glReadBuffer",
    "glReadPixels",
    "glRect",
    "glRenderMode",
    "glResetHistogram",
    "glResetMinmax",
    "glRotate",
    "glSampleCoverage",
    "glScale",
    "glScissor",
    "glSecondaryColorPointer",
    "glSecondaryColor",
    "glSelectBuffer",
    "glSeparableFilter2D",
    "glShadeModel",
    "glShaderSource",
    "glStencilFuncSeparate",
    "glStencilFunc",
    "glStencilMaskSeparate",
    "glStencilMask",
    "glStencilOpSeparate",
    "glStencilOp",
    "glTexCoordPointer",
    "glTexCoord",
    "glTexEnv",
    "glTexGen",
    "glTexImage1D",
    "glTexImage2D",
    "glTexImage3D",
    "glTexParameter",
    "glTexSubImage1D",
    "glTexSubImage2D",
    "glTexSubImage3D",
    "glTranslate",
    "gluBeginCurve",
    "gluBeginPolygon",
    "gluBeginSurface",
    "gluBeginTrim",
    "gluBuild1DMipmapLevels",
    "gluBuild1DMipmaps",
    "gluBuild2DMipmapLevels",
    "gluBuild2DMipmaps",
    "gluBuild3DMipmapLevels",
    "gluBuild3DMipmaps",
    "gluCheckExtension",
    "gluCylinder",
    "gluDeleteNurbsRenderer",
    "gluDeleteQuadric",
    "gluDeleteTess",
    "gluDisk",
    "gluEndCurve",
    "gluEndPolygon",
    "gluEndSurface",
    "gluEndTrim",
    "gluErrorString",
    "gluGetNurbsProperty",
    "gluGetString",
    "gluGetTessProperty",
    "gluLoadSamplingMatrices",
    "gluLookAt",
    "gluNewNurbsRenderer",
    "gluNewQuadric",
    "gluNewTess",
    "gluNextContour",
    "glUniform",
    "glUnmapBuffer",
    "gluNurbsCallbackDataEXT",
    "gluNurbsCallbackData",
    "gluNurbsCallback",
    "gluNurbsCurve",
    "gluNurbsProperty",
    "gluNurbsSurface",
    "gluOrtho2D",
    "gluPartialDisk",
    "gluPerspective",
    "gluPickMatrix",
    "gluProject",
    "gluPwlCurve",
    "gluQuadricCallback",
    "gluQuadricDrawStyle",
    "gluQuadricNormals",
    "gluQuadricOrientation",
    "gluQuadricTexture",
    "gluScaleImage",
    "glUseProgram",
    "gluSphere",
    "gluTessBeginContour",
    "gluTessBeginPolygon",
    "gluTessCallback",
    "gluTessEndContour",
    "gluTessEndPolygon",
    "gluTessNormal",
    "gluTessProperty",
    "gluTessVertex",
    "gluUnProject4",
    "gluUnProject",
    "glValidateProgram",
    "glVertexAttribPointer",
    "glVertexAttrib",
    "glVertexPointer",
    "glVertex",
    "glViewport",
    "glWindowPos",
    "glXChooseFBConfig",
    "glXChooseVisual",
    "glXCopyContext",
    "glXCreateContext",
    "glXCreateGLXPixmap",
    "glXCreateNewContext",
    "glXCreatePbuffer",
    "glXCreatePixmap",
    "glXCreateWindow",
    "glXDestroyContext",
    "glXDestroyGLXPixmap",
    "glXDestroyPbuffer",
    "glXDestroyPixmap",
    "glXDestroyWindow",
    "glXFreeContextEXT",
    "glXGetClientString",
    "glXGetConfig",
    "glXGetContextIDEXT",
    "glXGetCurrentContext",
    "glXGetCurrentDisplay",
    "glXGetCurrentDrawable",
    "glXGetCurrentReadDrawable",
    "glXGetFBConfigAttrib",
    "glXGetFBConfigs",
    "glXGetProcAddress",
    "glXGetSelectedEvent",
    "glXGetVisualFromFBConfig",
    "glXImportContextEXT",
    "glXIntro",
    "glXIsDirect",
    "glXMakeContextCurrent",
    "glXMakeCurrent",
    "glXQueryContextInfoEXT",
    "glXQueryContext",
    "glXQueryDrawable",
    "glXQueryExtensionsString",
    "glXQueryExtension",
    "glXQueryServerString",
    "glXQueryVersion",
    "glXSelectEvent",
    "glXSwapBuffers",
    "glXUseXFont",
    "glXWaitGL",
    "glXWaitX",
  ],

  "3.3": [
    "glActiveTexture",
    "glAttachShader",
    "glBeginConditionalRender",
    "glBeginQuery",
    "glBeginTransformFeedback",
    "glBindAttribLocation",
    "glBindBufferBase",
    "glBindBufferRange",
    "glBindBuffer",
    "glBindFragDataLocationIndexed",
    "glBindFragDataLocation",
    "glBindFramebuffer",
    "glBindRenderbuffer",
    "glBindSampler",
    "glBindTexture",
    "glBindVertexArray",
    "glBlendColor",
    "glBlendEquationSeparate",
    "glBlendEquation",
    "glBlendFuncSeparate",
    "glBlendFunc",
    "glBlitFramebuffer",
    "glBufferData",
    "glBufferSubData",
    "glCheckFramebufferStatus",
    "glClampColor",
    "glClearBuffer",
    "glClearColor",
    "glClearDepth",
    "glClearStencil",
    "glClear",
    "glClientWaitSync",
    "glColorMask",
    "glCompileShader",
    "glCompressedTexImage1D",
    "glCompressedTexImage2D",
    "glCompressedTexImage3D",
    "glCompressedTexSubImage1D",
    "glCompressedTexSubImage2D",
    "glCompressedTexSubImage3D",
    "glCopyBufferSubData",
    "glCopyTexImage1D",
    "glCopyTexImage2D",
    "glCopyTexSubImage1D",
    "glCopyTexSubImage2D",
    "glCopyTexSubImage3D",
    "glCreateProgram",
    "glCreateShader",
    "glCullFace",
    "glDeleteBuffers",
    "glDeleteFramebuffers",
    "glDeleteProgram",
    "glDeleteQueries",
    "glDeleteRenderbuffers",
    "glDeleteSamplers",
    "glDeleteShader",
    "glDeleteSync",
    "glDeleteTextures",
    "glDeleteVertexArrays",
    "glDepthFunc",
    "glDepthMask",
    "glDepthRange",
    "glDetachShader",
    "glDisablei",
    "glDisableVertexAttribArray",
    "glDisable",
    "glDrawArraysInstanced",
    "glDrawArrays",
    "glDrawBuffers",
    "glDrawBuffer",
    "glDrawElementsBaseVertex",
    "glDrawElementsInstancedBaseVertex",
    "glDrawElementsInstanced",
    "glDrawElements",
    "glDrawRangeElementsBaseVertex",
    "glDrawRangeElements",
    "glEnableVertexAttribArray",
    "glEnable",
    "glEndConditionalRender",
    "glEndQuery",
    "glEndTransformFeedback",
    "glFenceSync",
    "glFinish",
    "glFlushMappedBufferRange",
    "glFlush",
    "glFramebufferRenderbuffer",
    "glFramebufferTextureLayer",
    "glFramebufferTexture",
    "glFrontFace",
    "glGenBuffers",
    "glGenerateMipmap",
    "glGenFramebuffers",
    "glGenQueries",
    "glGenRenderbuffers",
    "glGenSamplers",
    "glGenTextures",
    "glGenVertexArrays",
    "glGetActiveAttrib",
    "glGetActiveUniformBlockName",
    "glGetActiveUniformBlock",
    "glGetActiveUniformName",
    "glGetActiveUniformsiv",
    "glGetActiveUniform",
    "glGetAttachedShaders",
    "glGetAttribLocation",
    "glGetBufferParameter",
    "glGetBufferPointerv",
    "glGetBufferSubData",
    "glGetCompressedTexImage",
    "glGetError",
    "glGetFragDataIndex",
    "glGetFragDataLocation",
    "glGetFramebufferAttachmentParameter",
    "glGetMultisample",
    "glGetProgramInfoLog",
    "glGetProgram",
    "glGetQueryiv",
    "glGetQueryObject",
    "glGetRenderbufferParameter",
    "glGetSamplerParameter",
    "glGetShaderInfoLog",
    "glGetShaderSource",
    "glGetShader",
    "glGetString",
    "glGetSync",
    "glGetTexImage",
    "glGetTexLevelParameter",
    "glGetTexParameter",
    "glGetTransformFeedbackVarying",
    "glGetUniformBlockIndex",
    "glGetUniformIndices",
    "glGetUniformLocation",
    "glGetUniform",
    "glGetVertexAttribPointerv",
    "glGetVertexAttrib",
    "glGet",
    "glHint",
    "glIsBuffer",
    "glIsEnabled",
    "glIsFramebuffer",
    "glIsProgram",
    "glIsQuery",
    "glIsRenderbuffer",
    "glIsSampler",
    "glIsShader",
    "glIsSync",
    "glIsTexture",
    "glIsVertexArray",
    "glLineWidth",
    "glLinkProgram",
    "glLogicOp",
    "glMapBufferRange",
    "glMapBuffer",
    "glMultiDrawArrays",
    "glMultiDrawElementsBaseVertex",
    "glMultiDrawElements",
    "glPixelStore",
    "glPointParameter",
    "glPointSize",
    "glPolygonMode",
    "glPolygonOffset",
    "glPrimitiveRestartIndex",
    "glProvokingVertex",
    "glQueryCounter",
    "glReadBuffer",
    "glReadPixels",
    "glRenderbufferStorageMultisample",
    "glRenderbufferStorage",
    "glSampleCoverage",
    "glSampleMaski",
    "glSamplerParameter",
    "glScissor",
    "glShaderSource",
    "glStencilFuncSeparate",
    "glStencilFunc",
    "glStencilMaskSeparate",
    "glStencilMask",
    "glStencilOpSeparate",
    "glStencilOp",
    "glTexBuffer",
    "glTexImage1D",
    "glTexImage2DMultisample",
    "glTexImage2D",
    "glTexImage3DMultisample",
    "glTexImage3D",
    "glTexParameter",
    "glTexSubImage1D",
    "glTexSubImage2D",
    "glTexSubImage3D",
    "glTransformFeedbackVaryings",
    "glUniformBlockBinding",
    "glUniform",
    "glUnmapBuffer",
    "glUseProgram",
    "glValidateProgram",
    "glVertexAttribDivisor",
    "glVertexAttribPointer",
    "glVertexAttrib",
    "glViewport",
    "glWaitSync",
  ],

  "4.4": [
    "glActiveShaderProgram",
    "glActiveTexture",
    "glAttachShader",
    "glBeginConditionalRender",
    "glBeginQueryIndexed",
    "glBeginQuery",
    "glBeginTransformFeedback",
    "glBindAttribLocation",
    "glBindBufferBase",
    "glBindBufferRange",
    "glBindBuffersBase",
    "glBindBuffersRange",
    "glBindBuffer",
    "glBindFragDataLocationIndexed",
    "glBindFragDataLocation",
    "glBindFramebuffer",
    "glBindImageTextures",
    "glBindImageTexture",
    "glBindProgramPipeline",
    "glBindRenderbuffer",
    "glBindSamplers",
    "glBindSampler",
    "glBindTextures",
    "glBindTextureUnit",
    "glBindTexture",
    "glBindTransformFeedback",
    "glBindVertexArray",
    "glBindVertexBuffers",
    "glBindVertexBuffer",
    "glBlendColor",
    "glBlendEquationSeparate",
    "glBlendEquation",
    "glBlendFuncSeparate",
    "glBlendFunc",
    "glBlitFramebuffer",
    "glBufferData",
    "glBufferStorage",
    "glBufferSubData",
    "glCheckFramebufferStatus",
    "glClampColor",
    "glClearBufferData",
    "glClearBufferSubData",
    "glClearBuffer",
    "glClearColor",
    "glClearDepth",
    "glClearStencil",
    "glClearTexImage",
    "glClearTexSubImage",
    "glClear",
    "glClientWaitSync",
    "glClipControl",
    "glColorMask",
    "glCompileShader",
    "glCompressedTexImage1D",
    "glCompressedTexImage2D",
    "glCompressedTexImage3D",
    "glCompressedTexSubImage1D",
    "glCompressedTexSubImage2D",
    "glCompressedTexSubImage3D",
    "glCopyBufferSubData",
    "glCopyImageSubData",
    "glCopyTexImage1D",
    "glCopyTexImage2D",
    "glCopyTexSubImage1D",
    "glCopyTexSubImage2D",
    "glCopyTexSubImage3D",
    "glCreateBuffers",
    "glCreateFramebuffers",
    "glCreateProgramPipelines",
    "glCreateProgram",
    "glCreateQueries",
    "glCreateRenderbuffers",
    "glCreateSamplers",
    "glCreateShaderProgram",
    "glCreateShader",
    "glCreateTextures",
    "glCreateTransformFeedbacks",
    "glCreateVertexArrays",
    "glCullFace",
    "glDebugMessageCallback",
    "glDebugMessageControl",
    "glDebugMessageInsert",
    "glDeleteBuffers",
    "glDeleteFramebuffers",
    "glDeleteProgramPipelines",
    "glDeleteProgram",
    "glDeleteQueries",
    "glDeleteRenderbuffers",
    "glDeleteSamplers",
    "glDeleteShader",
    "glDeleteSync",
    "glDeleteTextures",
    "glDeleteTransformFeedbacks",
    "glDeleteVertexArrays",
    "glDepthFunc",
    "glDepthMask",
    "glDepthRangeArray",
    "glDepthRangeIndexed",
    "glDepthRange",
    "glDetachShader",
    "glDisableVertexAttribArray",
    "glDispatchComputeIndirect",
    "glDispatchCompute",
    "glDrawArraysIndirect",
    "glDrawArraysInstancedBaseInstance",
    "glDrawArraysInstanced",
    "glDrawArrays",
    "glDrawBuffers",
    "glDrawBuffer",
    "glDrawElementsBaseVertex",
    "glDrawElementsIndirect",
    "glDrawElementsInstancedBaseInstance",
    "glDrawElementsInstancedBaseVertexBaseInstance",
    "glDrawElementsInstancedBaseVertex",
    "glDrawElementsInstanced",
    "glDrawElements",
    "glDrawRangeElementsBaseVertex",
    "glDrawRangeElements",
    "glDrawTransformFeedbackInstanced",
    "glDrawTransformFeedbackStreamInstanced",
    "glDrawTransformFeedbackStream",
    "glDrawTransformFeedback",
    "glEnableVertexAttribArray",
    "glEnable",
    "glEndConditionalRender",
    "glEndTransformFeedback",
    "glEndQuery",
    "glFenceSync",
    "glFinish",
    "glFlushMappedBufferRange",
    "glFlush",
    "glFramebufferParameteri",
    "glFramebufferRenderbuffer",
    "glFramebufferTextureLayer",
    "glFramebufferTexture",
    "glFrontFace",
    "glGenBuffers",
    "glGenerateMipmap",
    "glGenFramebuffers",
    "glGenProgramPipelines",
    "glGenQueries",
    "glGenRenderbuffers",
    "glGenSamplers",
    "glGenTextures",
    "glGenTransformFeedbacks",
    "glGenVertexArrays",
    "glGetActiveAtomicCounterBufferiv",
    "glGetActiveAttrib",
    "glGetActiveSubroutineName",
    "glGetActiveSubroutineUniformName",
    "glGetActiveSubroutineUniform",
    "glGetActiveUniformBlockName",
    "glGetActiveUniformBlock",
    "glGetActiveUniformName",
    "glGetActiveUniformsiv",
    "glGetActiveUniform",
    "glGetAttachedShaders",
    "glGetAttribLocation",
    "glGetBufferParameter",
    "glGetBufferPointerv",
    "glGetBufferSubData",
    "glGetCompressedTexImage",
    "glGetCompressedTextureSubImage",
    "glGetDebugMessageLog",
    "glGetError",
    "glGetFragDataIndex",
    "glGetFragDataLocation",
    "glGetFramebufferAttachmentParameter",
    "glGetFramebufferParameter",
    "glGetGraphicsResetStatus",
    "glGetInternalformat",
    "glGetMultisample",
    "glGetObjectLabel",
    "glGetObjectPtrLabel",
    "glGetPointerv",
    "glGetProgramBinary",
    "glGetProgramInfoLog",
    "glGetProgramInterface",
    "glGetProgramPipelineInfoLog",
    "glGetProgramPipeline",
    "glGetProgramResourceIndex",
    "glGetProgramResourceLocationIndex",
    "glGetProgramResourceLocation",
    "glGetProgramResourceName",
    "glGetProgramResource",
    "glGetProgramStage",
    "glGetProgram",
    "glGetQueryIndexed",
    "glGetQueryiv",
    "glGetQueryObject",
    "glGetRenderbufferParameter",
    "glGetSamplerParameter",
    "glGetShaderInfoLog",
    "glGetShaderPrecisionFormat",
    "glGetShaderSource",
    "glGetShader",
    "glGetString",
    "glGetSubroutineIndex",
    "glGetSubroutineUniformLocation",
    "glGetSync",
    "glGetTexImage",
    "glGetTexLevelParameter",
    "glGetTexParameter",
    "glGetTextureSubImage",
    "glGetTransformFeedbackVarying",
    "glGetTransformFeedback",
    "glGetUniformBlockIndex",
    "glGetUniformIndices",
    "glGetUniformLocation",
    "glGetUniformSubroutine",
    "glGetUniform",
    "glGetVertexArrayIndexed",
    "glGetVertexArrayiv",
    "glGetVertexAttribPointerv",
    "glGetVertexAttrib",
    "glGet",
    "glHint",
    "glInvalidateBufferData",
    "glInvalidateBufferSubData",
    "glInvalidateFramebuffer",
    "glInvalidateSubFramebuffer",
    "glInvalidateTexImage",
    "glInvalidateTexSubImage",
    "glIsBuffer",
    "glIsEnabled",
    "glIsFramebuffer",
    "glIsProgramPipeline",
    "glIsProgram",
    "glIsQuery",
    "glIsRenderbuffer",
    "glIsSampler",
    "glIsShader",
    "glIsSync",
    "glIsTexture",
    "glIsTransformFeedback",
    "glIsVertexArray",
    "glLineWidth",
    "glLinkProgram",
    "glLogicOp",
    "glMapBufferRange",
    "glMapBuffer",
    "glMemoryBarrier",
    "glMinSampleShading",
    "glMultiDrawArraysIndirect",
    "glMultiDrawArrays",
    "glMultiDrawElementsBaseVertex",
    "glMultiDrawElementsIndirect",
    "glMultiDrawElements",
    "glObjectLabel",
    "glObjectPtrLabel",
    "glPatchParameter",
    "glPauseTransformFeedback",
    "glPixelStore",
    "glPointParameter",
    "glPointSize",
    "glPolygonMode",
    "glPolygonOffset",
    "glPopDebugGroup",
    "glPrimitiveRestartIndex",
    "glProgramBinary",
    "glProgramParameter",
    "glProgramUniform",
    "glProvokingVertex",
    "glPushDebugGroup",
    "glQueryCounter",
    "glReadBuffer",
    "glReadPixels",
    "glReleaseShaderCompiler",
    "glRenderbufferStorageMultisample",
    "glRenderbufferStorage",
    "glResumeTransformFeedback",
    "glSampleCoverage",
    "glSampleMaski",
    "glSamplerParameter",
    "glScissorArray",
    "glScissorIndexed",
    "glScissor",
    "glShaderBinary",
    "glShaderSource",
    "glShaderStorageBlockBinding",
    "glStencilFuncSeparate",
    "glStencilFunc",
    "glStencilMaskSeparate",
    "glStencilMask",
    "glStencilOpSeparate",
    "glStencilOp",
    "glTexBufferRange",
    "glTexBuffer",
    "glTexImage1D",
    "glTexImage2DMultisample",
    "glTexImage2D",
    "glTexImage3DMultisample",
    "glTexImage3D",
    "glTexParameter",
    "glTexStorage1D",
    "glTexStorage2DMultisample",
    "glTexStorage2D",
    "glTexStorage3DMultisample",
    "glTexStorage3D",
    "glTexSubImage1D",
    "glTexSubImage2D",
    "glTexSubImage3D",
    "glTextureBarrier",
    "glTextureView",
    "glTransformFeedbackBufferBase",
    "glTransformFeedbackBufferRange",
    "glTransformFeedbackVaryings",
    "glUniformBlockBinding",
    "glUniformSubroutines",
    "glUniform",
    "glUnmapBuffer",
    "glUseProgramStages",
    "glUseProgram",
    "glValidateProgramPipeline",
    "glValidateProgram",
    "glVertexArrayElementBuffer",
    "glVertexAttribBinding",
    "glVertexAttribDivisor",
    "glVertexAttribFormat",
    "glVertexAttribPointer",
    "glVertexAttrib",
    "glVertexBindingDivisor",
    "glViewportArray",
    "glViewportIndexed",
    "glViewport",
    "glWaitSync",
  ],
}

version_glsl = {
  "4.4": [
    "abs",
    "acosh",
    "acos",
    "all",
    "any",
    "asinh",
    "asin",
    "atanh",
    "atan",
    "atomicAdd",
    "atomicAnd",
    "atomicCompSwap",
    "atomicCounterDecrement",
    "atomicCounterIncrement",
    "atomicCounter",
    "atomicExchange",
    "atomicMax",
    "atomicMin",
    "atomicOr",
    "atomicXor",
    "barrier",
    "bitCount",
    "bitfieldExtract",
    "bitfieldInsert",
    "bitfieldReverse",
    "ceil",
    "clamp",
    "cosh",
    "cos",
    "cross",
    "degrees",
    "determinant",
    "dFdx",
    "distance",
    "dot",
    "EmitStreamVertex",
    "EmitVertex",
    "EndPrimitive",
    "EndStreamPrimitive",
    "equal",
    "exp2",
    "exp",
    "faceforward",
    "findLSB",
    "findMSB",
    "floatBitsToInt",
    "floor",
    "fma",
    "fract",
    "frexp",
    "fwidth",
    "greaterThanEqual",
    "greaterThan",
    "groupMemoryBarrier",
    "imageAtomicAdd",
    "imageAtomicAnd",
    "imageAtomicCompSwap",
    "imageAtomicExchange",
    "imageAtomicMax",
    "imageAtomicMin",
    "imageAtomicOr",
    "imageAtomicXor",
    "imageLoad",
    "imageSamples",
    "imageSize",
    "imageStore",
    "intBitsToFloat",
    "interpolateAtCentroid",
    "interpolateAtOffset",
    "interpolateAtSample",
    "inversesqrt",
    "inverse",
    "isinf",
    "isnan",
    "ldexp",
    "length",
    "lessThanEqual",
    "lessThan",
    "log2",
    "log",
    "matrixCompMult",
    "max",
    "memoryBarrierAtomicCounter",
    "memoryBarrierBuffer",
    "memoryBarrierImage",
    "memoryBarrierShared",
    "memoryBarrier",
    "min",
    "mix",
    "modf",
    "mod",
    "noise",
    "normalize",
    "notEqual",
    "not",
    "outerProduct",
    "packDouble2x32",
    "packHalf2x16",
    "packUnorm",
    "pow",
    "radians",
    "reflect",
    "refract",
    "removedTypes",
    "roundEven",
    "round",
    "sign",
    "sinh",
    "sin",
    "smoothstep",
    "sqrt",
    "step",
    "tanh",
    "tan",
    "texelFetchOffset",
    "texelFetch",
    "textureGatherOffsets",
    "textureGatherOffset",
    "textureGather",
    "textureGradOffset",
    "textureGrad",
    "textureLodOffset",
    "textureLod",
    "textureOffset",
    "textureProjGradOffset",
    "textureProjGrad",
    "textureProjLodOffset",
    "textureProjLod",
    "textureProjOffset",
    "textureProj",
    "textureQueryLevels",
    "textureQueryLod",
    "textureSamples",
    "textureSize",
    "texture",
    "transpose",
    "trunc",
    "uaddCarry",
    "umulExtended",
    "unpackDouble2x32",
    "unpackHalf2x16",
    "unpackUnorm",
    "usubBorrow",
    "gl_ClipDistance",
    "gl_CullDistance",
    "gl_FragCoord",
    "gl_FragDepth",
    "gl_FrontFacing",
    "gl_GlobalInvocationID",
    "gl_HelperInvocation",
    "gl_InstanceID",
    "gl_InvocationID",
    "gl_Layer",
    "gl_LocalInvocationID",
    "gl_LocalInvocationIndex",
    "gl_NumSamples",
    "gl_NumWorkGroups",
    "gl_PatchVerticesIn",
    "gl_PointCoord",
    "gl_PointSize",
    "gl_Position",
    "gl_PrimitiveIDIn",
    "gl_PrimitiveID",
    "gl_SampleID",
    "gl_SampleMaskIn",
    "gl_SampleMask",
    "gl_SamplePosition",
    "gl_TessCoord",
    "gl_TessLevelInner",
    "gl_TessLevelOuter",
    "gl_VertexID",
    "gl_ViewportIndex",
    "gl_WorkGroupID",
    "gl_WorkGroupSize",
  ],
}

commands_version = {}
glsl_version = {}

def reverse_version_index(command_list):
  reversed = {}
  
  for version in command_list:
    for command in command_list[version]:
      if not command in reversed:
        reversed[command] = []

      reversed[command].append(version)

  return reversed

def reverse_versions():
  global commands_version
  global glsl_version
  print "Generating version index..."
  commands_version = reverse_version_index(version_commands)
  glsl_version = reverse_version_index(version_glsl)
  print "Done."

command_categories = OrderedDict([
  ( "Textures", [
    "glBindTexture", "glTexImage1D", "glTexImage2D", "glTexImage2DMultisample", "glTexImage3D",
    "glTexImage3DMultisample", "glTexParameter", "glCopyTexImage1D", "glCopyTexImage2D",
    "glCopyTexSubImage1D", "glCopyTexSubImage2D", "glCopyTexSubImage3D"
  ] ),
  ( "Immediate Mode", [
    # Stuff you can call between glBegin and glEnd
    "glBegin", "glEnd", "glVertex", "glColor", "glTexCoord", "glFogCoord", "glIndex", "glMaterial",
    "glMultiTexCoord", "glNormal", "glSecondaryColor", "glArrayElement", "glEvalCoord", "glEvalMesh",
    "glEvalPoint"
  ] ),
  ( "GL2 Rasterization", [
    # Anything render related that doesn't exist anymore
    "glRenderMode", "glFeedbackBuffer", "glPushName", "glLoadName", "glPassThrough", "glSelectBuffer",
    "glInitNames", "glLineStipple", "glPolygonStipple", "glDrawPixels", "glCopyPixels", "glRasterPos",
    "glWindowPos", "glRect", "glBitmap", "glClipPlane", "glClearIndex", "glColorTable", "glColorSubTable",
    "glColorTableParameter", "glCopyColorTable", "glCopyColorSubTable", "glGetColorTable",
    "glGetColorTableParameter", "glConvolutionFilter1D", "glConvolutionFilter2D", "glConvolutionParameter",
    "glCopyConvolutionFilter1D", "glCopyConvolutionFilter2D", "glFog", "glGetClipPlane",
    "glGetConvolutionFilter", "glGetConvolutionParameter", "glGetHistogram", "glGetHistogramParameter",
    "glGetMap", "glGetPixelMap", "glGetPolygonStipple", "glGetSeparableFilter", "glHistogram",
    "glMap1", "glMap2", "glMapGrid", "glPopName", "glPixelZoom", "glResetHistogram",
    "glSeparableFilter2D"
  ] ),
  ( "Client Arrays", [
    "glVertexPointer", "glEnableClientState", "glDisableClientState", "glFogCoordPointer",
    "glIndexPointer", "glInterleavedArrays", "glNormalPointer", "glPopClientAttrib", "glPushClientAttrib",
    "glSecondaryColorPointer", "glColorPointer", "glTexCoordPointer",
  ] ),
  ( "Fixed Function", [
    # Stuff that got moved into shaders
    "glEdgeFlag", "glEdgeFlagPointer", "glAlphaFunc", "glLight", "glColorMaterial",
    "glLightModel", "glAccum", "glClearAccum", "glGetLight", "glGetMaterial", "glGetMinmax",
    "glGetMinmaxParameter", "glGetTexEnv", "glTexEnv", "glTexGen", "glGetTexGen", "glIndexMask",
    "glMinmax", "glPushAttrib", "glPopAttrib", "glResetMinmax", "glShadeModel"
  ] ),
  ( "Matrix State", [
    "glLoadMatrix", "glLoadIdentity", "glMatrixMode", "glMultMatrix", "glMultTransposeMatrix",
    "glPushMatrix", "glPopMatrix", "glLoadTransposeMatrix", "glFrustum", "glOrtho", "glRotate",
    "glScale", "glTranslate"
  ] ),
  ( "GL2 Textures", [
    "glAreTexturesResident", "glPrioritizeTextures", "glClientActiveTexture", "glPixelMap",
    "glPixelTransfer"
  ] ),
  ( "Call Lists", [
    "glCallList", "glCallLists", "glIsList", "glDeleteLists", "glGenLists", "glNewList", "glEndList",
    "glListBase"
  ] ),
  ( "GLX", [
    "glXChooseFBConfig", "glXChooseVisual", "glXCopyContext", "glXCreateContext", "glXCreateGLXPixmap",
    "glXCreateNewContext", "glXCreatePbuffer", "glXCreatePixmap", "glXCreateWindow", "glXDestroyContext",
    "glXDestroyGLXPixmap", "glXDestroyPbuffer", "glXDestroyPixmap", "glXDestroyWindow",
    "glXFreeContextEXT", "glXGetClientString", "glXGetConfig", "glXGetContextIDEXT",
    "glXGetCurrentContext", "glXGetCurrentDisplay", "glXGetCurrentDrawable", "glXGetCurrentReadDrawable",
    "glXGetFBConfigAttrib", "glXGetFBConfigs", "glXGetProcAddress", "glXGetSelectedEvent",
    "glXGetVisualFromFBConfig", "glXImportContextEXT", "glXIntro", "glXIsDirect", "glXMakeContextCurrent",
    "glXMakeCurrent", "glXQueryContextInfoEXT", "glXQueryContext", "glXQueryDrawable",
    "glXQueryExtensionsString", "glXQueryExtension", "glXQueryServerString", "glXQueryVersion",
    "glXSelectEvent", "glXSwapBuffers", "glXUseXFont", "glXWaitGL", "glXWaitX",
  ] ),
  ( "GLU", [
    "gluBeginCurve", "gluBeginPolygon", "gluBeginSurface", "gluBeginTrim", "gluBuild1DMipmapLevels",
    "gluBuild1DMipmaps", "gluBuild2DMipmapLevels", "gluBuild2DMipmaps", "gluBuild3DMipmapLevels",
    "gluBuild3DMipmaps", "gluCheckExtension", "gluCylinder", "gluDeleteNurbsRenderer", "gluDeleteQuadric",
    "gluDeleteTess", "gluDisk", "gluEndCurve", "gluEndPolygon", "gluEndSurface", "gluEndTrim",
    "gluErrorString", "gluGetNurbsProperty", "gluGetString", "gluGetTessProperty",
    "gluLoadSamplingMatrices", "gluLookAt", "gluNewNurbsRenderer", "gluNewQuadric", "gluNewTess",
    "gluNextContour", "gluNurbsCallbackDataEXT", "gluNurbsCallbackData", "gluNurbsCallback",
    "gluNurbsCurve", "gluNurbsProperty", "gluNurbsSurface", "gluOrtho2D", "gluPartialDisk",
    "gluPerspective", "gluPickMatrix", "gluProject", "gluPwlCurve", "gluQuadricCallback",
    "gluQuadricDrawStyle", "gluQuadricNormals", "gluQuadricOrientation", "gluQuadricTexture",
    "gluScaleImage", "gluSphere", "gluTessBeginContour", "gluTessBeginPolygon", "gluTessCallback",
    "gluTessEndContour", "gluTessEndPolygon", "gluTessNormal", "gluTessProperty", "gluTessVertex",
    "gluUnProject4", "gluUnProject",
  ] ),
])

reverse_versions()

def get_major_versions_available(command):
  global commands_version

  versions_available = commands_version[command]
  versions_available.sort()
    
  major_versions = []
  for v in versions_available:
    major_version = v[0]
    if not major_version in major_versions:
      major_versions.append(major_version)
      
  return major_versions
